import productImg1 from "./images/product1.webp";
import productImg2 from "./images/product2.webp";
import productImg3 from "./images/product3.webp";
import productImg4 from "./images/product4.webp";
import productImg5 from "./images/product5.webp";
import productImg6 from "./images/product6.webp";
import productImg7 from "./images/product7.webp";
import productImg8 from "./images/product8.webp";

export const productsData = [
  {
    id: 1,
    title: "Paco Rabanne",
    price: 50.0,
    img: productImg1,
    type: "men",
    rating: 4,
    size: 4.5,
    fragrance: "Cardamom",
    yearIntroduced: 1990,
    desc: "Hurley Dry-Fit Chino Short. Men's chino short. Outseam Length: 19 Dri-FIT Technology helps keep you dry and comfortable. Made with sweat-wicking fabric. Fitted waist with belt loops. Button waist with zip fly provides a classic look and feel . Back welt pockets and coin pocket for storage. Dual side seam pockets. Heat transferred logos. 70% nylon 24% polyester 6% spandex. Imported.",
  },
  {
    id: 2,
    title: "Luna",
    price: 30.0,
    img: productImg2,
    type: "men",
    rating: 5,
    size: 4.5,
    fragrance: "Cardamom",
    yearIntroduced: 1990,
    desc: "Hurley Dry-Fit Chino Short. Men's chino short. Outseam Length: 19 Dri-FIT Technology helps keep you dry and comfortable. Made with sweat-wicking fabric. Fitted waist with belt loops. Button waist with zip fly provides a classic look and feel . Back welt pockets and coin pocket for storage. Dual side seam pockets. Heat transferred logos. 70% nylon 24% polyester 6% spandex. Imported.",
  },
  {
    id: 3,
    title: "Marc Jacobs",
    price: 49.0,
    img: productImg3,
    type: "women",
    rating: 3,
    size: 4.5,
    fragrance: "Cardamom",
    yearIntroduced: 1990,
    desc: "Hurley Dry-Fit Chino Short. Men's chino short. Outseam Length: 19 Dri-FIT Technology helps keep you dry and comfortable. Made with sweat-wicking fabric. Fitted waist with belt loops. Button waist with zip fly provides a classic look and feel . Back welt pockets and coin pocket for storage. Dual side seam pockets. Heat transferred logos. 70% nylon 24% polyester 6% spandex. Imported.",
  },
  {
    id: 4,
    title: "Gabbana Light",
    price: 35.0,
    img: productImg4,
    type: "women",
    rating: 4,
    yearIntroduced: 1990,
    desc: "Hurley Dry-Fit Chino Short. Men's chino short. Outseam Length: 19 Dri-FIT Technology helps keep you dry and comfortable. Made with sweat-wicking fabric. Fitted waist with belt loops. Button waist with zip fly provides a classic look and feel . Back welt pockets and coin pocket for storage. Dual side seam pockets. Heat transferred logos. 70% nylon 24% polyester 6% spandex. Imported.",
  },
  {
    id: 5,
    title: "Swiss Arabian",
    price: 48.0,
    img: productImg5,
    type: "men",
    rating: 4,
    size: 4.5,
    fragrance: "Cardamom",
    desc: "Hurley Dry-Fit Chino Short. Men's chino short. Outseam Length: 19 Dri-FIT Technology helps keep you dry and comfortable. Made with sweat-wicking fabric. Fitted waist with belt loops. Button waist with zip fly provides a classic look and feel . Back welt pockets and coin pocket for storage. Dual side seam pockets. Heat transferred logos. 70% nylon 24% polyester 6% spandex. Imported.",
  },
  {
    id: 6,
    title: "Fantasy",
    price: 76.0,
    img: productImg6,
    type: "women",
    rating: 2,
    size: 4.5,
    fragrance: "Cardamom",
    desc: "Hurley Dry-Fit Chino Short. Men's chino short. Outseam Length: 19 Dri-FIT Technology helps keep you dry and comfortable. Made with sweat-wicking fabric. Fitted waist with belt loops. Button waist with zip fly provides a classic look and feel . Back welt pockets and coin pocket for storage. Dual side seam pockets. Heat transferred logos. 70% nylon 24% polyester 6% spandex. Imported.",
  },
  {
    id: 7,
    title: "Mademosllas",
    price: 23.0,
    img: productImg7,
    type: "women",
    rating: 4,
    size: 4.5,
    fragrance: "Cardamom",
    yearIntroduced: 1990,
    desc: "Hurley Dry-Fit Chino Short. Men's chino short. Outseam Length: 19 Dri-FIT Technology helps keep you dry and comfortable. Made with sweat-wicking fabric. Fitted waist with belt loops. Button waist with zip fly provides a classic look and feel . Back welt pockets and coin pocket for storage. Dual side seam pockets. Heat transferred logos. 70% nylon 24% polyester 6% spandex. Imported.",
  },
  {
    id: 8,
    title: "Est Belle",
    price: 53.0,
    img: productImg8,
    type: "men",
    rating: 4,
    size: 4.5,
    fragrance: "Cardamom",
    yearIntroduced: 1990,
    desc: "Hurley Dry-Fit Chino Short. Men's chino short. Outseam Length: 19 Dri-FIT Technology helps keep you dry and comfortable. Made with sweat-wicking fabric. Fitted waist with belt loops. Button waist with zip fly provides a classic look and feel . Back welt pockets and coin pocket for storage. Dual side seam pockets. Heat transferred logos. 70% nylon 24% polyester 6% spandex. Imported.",
  },
];

export const usersData = [
  {
    id: 1,
    username: "karim altohamy",
    email: "karim2002@gmail.com",
    country: "Egypt",
    city: "cairo",
    phone: "0100478587",
  },
  {
    id: 2,
    username: "awad mohammed",
    email: "awad221@gmail.com",
    country: "Egypt",
    city: "cairo",
    phone: "0100478587",
  },
  {
    id: 3,
    username: "ibra mohammed",
    email: "ibra321@gmail.com",
    country: "Egypt",
    city: "cairo",
    phone: "0100478587",
  },
];

export const ordersData = [
  {
    id: 1,
    name: "karim altohamy",
    email: "example@example.com",
    city: "cairo",
    governorate: "cairo",
    postalCode: 153,
    title: "Paco Rabanne",
    price: 250,
    address: "cairo, egypt",
    type: "men",
    rating: 4,
    size: 4.5,
    fragrance: "Cardamom",
    yearIntroduced: 1990,
    desc: "Hurley Dry-Fit Chino Short. Men's chino short. Outseam Length: 19 Dri-FIT Technology helps keep you dry and comfortable. Made with sweat-wicking fabric. Fitted waist with belt loops. Button waist with zip fly provides a classic look and feel . Back welt pockets and coin pocket for storage. Dual side seam pockets. Heat transferred logos. 70% nylon 24% polyester 6% spandex. Imported.",
  },
  {
    id: 2,
    name: "khaled mohammed",
    email: "example@example.com",
    city: "cairo",
    governorate: "cairo",
    postalCode: 253,
    title: "Est Belle",
    price: 127,
    address: "cairo, egypt",
    type: "men",
    rating: 3,
    size: 4.5,
    fragrance: "Cardamom",
    yearIntroduced: 1990,
    desc: "Hurley Dry-Fit Chino Short. Men's chino short. Outseam Length: 19 Dri-FIT Technology helps keep you dry and comfortable. Made with sweat-wicking fabric. Fitted waist with belt loops. Button waist with zip fly provides a classic look and feel . Back welt pockets and coin pocket for storage. Dual side seam pockets. Heat transferred logos. 70% nylon 24% polyester 6% spandex. Imported.",
  },
  {
    id: 3,
    name: "awad ahmed",
    email: "example@example.com",
    city: "cairo",
    governorate: "cairo",
    postalCode: 253,
    title: "Paco Rabanne",
    price: 127,
    address: "cairo, egypt",
    type: "men",
    rating: 3,
    size: 4.5,
    fragrance: "Cardamom",
    yearIntroduced: 1990,
    desc: "Hurley Dry-Fit Chino Short. Men's chino short. Outseam Length: 19 Dri-FIT Technology helps keep you dry and comfortable. Made with sweat-wicking fabric. Fitted waist with belt loops. Button waist with zip fly provides a classic look and feel . Back welt pockets and coin pocket for storage. Dual side seam pockets. Heat transferred logos. 70% nylon 24% polyester 6% spandex. Imported.",
  },
  {
    id: 4,
    name: "ibra mohammed",
    email: "example@example.com",
    city: "cairo",
    governorate: "cairo",
    postalCode: 253,
    title: "Est Belle",
    price: 127,
    address: "cairo, egypt",
    type: "men",
    rating: 3,
    size: 4.5,
    fragrance: "Cardamom",
    yearIntroduced: 1990,
    desc: "Hurley Dry-Fit Chino Short. Men's chino short. Outseam Length: 19 Dri-FIT Technology helps keep you dry and comfortable. Made with sweat-wicking fabric. Fitted waist with belt loops. Button waist with zip fly provides a classic look and feel . Back welt pockets and coin pocket for storage. Dual side seam pockets. Heat transferred logos. 70% nylon 24% polyester 6% spandex. Imported.",
  },
];
